backend:
  name: github
  repo: jinjcovsky/jinjcovsky.github.io
  branch: main
  base_url: https://woistjan-proxy.jkienast-at.workers.dev

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "frontmatter"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Coordinates", name: "coords", widget: "string", hint: "Comma-separated coordinates, for example: 47.45677,11.90284", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
